#!/bin/bash

# none of su/sudo/runuser/s6-setuidgid/etc/etc/etc actually change HOME
# to the home of the user you run as. Setting manually while keeping 

# tmp_dir=$(mktemp)
# cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst
# source /etc/profile.d/0000-env.sh

# grab the username
source /etc/profile.d/0000-env.sh
eval $(cat /etc/cont-init.d/001-userconf.sh  | grep -E "^export USER_NAME" | envsubst)

echo "-----------------------------------------------------------"
echo "Running code-server as: ${USER_NAME:=liveware}"
su - ${USER_NAME} -c 'id'
echo "-----------------------------------------------------------"
#echo "# s6-setuidgid $USER /usr/local/bin/code-server --disable-update-check --bind-addr 0.0.0.0:8080 $HOME"
#s6-setuidgid ${USER_NAME} /usr/local/bin/code-server --disable-update-check --bind-addr 0.0.0.0:8080 ${USER_HOME}

su - ${USER_NAME} -c '
    /usr/local/bin/code-server --disable-update-check --bind-addr 0.0.0.0:8080 ${HOME}
'



